version: 2
jobs:
  build:
    docker:
      - image: osseed/drupal8:latest
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: drupal
          MYSQL_ROOT_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
    working_directory: ~/drupal-circleci
    steps:
      - checkout:
      - run:
          name: "Install Dependencies"
          command: |
            composer install
      - run:
          name: "Site Setup"
          command: |
            cp .circleci/env/settings.local.php web/sites/default/
            ./vendor/bin/drush site-install minimal -y --verbose
