version: 2
jobs:
  build:
    environment:
      DRUPAL_DB: drupal
      DB_USER: root
      DB_PWD: root
      DB_HOST: 127.0.0.1
    docker:
      - image: drupaldocker/php:7.2-cli-2.x
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: $DRUPAL_DB
          MYSQL_ROOT_USERNAME: $DB_USER
          MYSQL_ROOT_PASSWORD: $DB_PWD
          MYSQL_ROOT_HOST: "%"
    working_directory: ~/drupal-circleci
    steps:
      - checkout:
      - run:
          name: "Updating Composer"
          command: |
            composer self-update
      - run:
          name: "Install Dependencies"
          command: |
            composer install
      - run:
          name: "Site Setup"
          command: |
            echo "mysql://$DB_USER:$DB_PWD@$DB_HOST/$DRUPAL_DB"
            cp .circleci/env/settings.local.php web/sites/default/
            ./vendor/bin/drush site-install minimal --db-url="mysql://$DB_USER:$DB_PWD@$DB_HOST/$DRUPAL_DB" -y --verbose
