version: 2
jobs:
  build:
    docker:
      - image: registry.gitlab.com/janpoboril/drupal-composer-docker:7.2-apache
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: drupal
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
    environment:
      BLUEMIX_ORG: CircleCI
      BLUEMIX_SPACE: dev
    steps:
      - checkout:
      - run:
          name: "Updating Composer"
          command: |
            composer self-update
      - run:
          name: "Install Dependencies"
          command: |
            composer install
      - run:
          name: "Site Setup"
          command: |
            vendor/bin/drush site-install minimal --db-url="mysql://root:root@localhost/drupal"
