version: 2
jobs:
  build:
    docker:
      - image: registry.gitlab.com/janpoboril/drupal-composer-docker:7.2-apache
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: drupal
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
    working_directory: ~/drupal-circleci
    steps:
      - checkout:
      - run:
          name: "Updating Composer"
          command: |
            composer self-update
      - run:
          name: "Install Dependencies"
          command: |
            composer install
      - run:
          name: "Install Drush"
          command: |
            wget -O drush.phar https://github.com/drush-ops/drush-launcher/releases/download/0.4.2/drush.phar
            chmod +x drush.phar
            mv drush.phar /usr/local/bin/drush
      - run:
          name: "Site Setup"
          command: |
            drush site-install minimal --db-url="mysql://root:root@localhost/drupal" -y --verbose
